"""add role and sessions

Revision ID: 0c73b66f6776
Revises: 7b535559c695
Create Date: 2026-06-22 18:22:49.435693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c73b66f6776'
down_revision: Union[str, Sequence[str], None] = '7b535559c695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('role', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'customers', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'role')
    # ### end Alembic commands ###
