"""banking tables

Revision ID: f8978766ed52
Revises: 43b0c2e9d9da
Create Date: 2026-06-23 11:46:18.888919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8978766ed52'
down_revision: Union[str, Sequence[str], None] = '43b0c2e9d9da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('accounts', 'account_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'accounts', 'customers', ['customer_id'], ['customer_id'])
    op.add_column('transactions', sa.Column('reference_number', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['reference_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'created_at')
    op.drop_column('transactions', 'reference_number')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.alter_column('accounts', 'account_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('accounts', 'created_at')
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('sessions_customer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('sessions_pkey'))
    )
    # ### end Alembic commands ###
